version: '3.8'

services:
  api:
    build: .
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    ports:
      - "9902:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    gpus: all  

  mongo:
    image: mongo:6.0
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE:     "${MONGO_DATABASE}"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  mongo-express:
    image: mongo-express:1.0.0
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "9802:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER:          mongo
      ME_CONFIG_MONGODB_PORT:            27017
      ME_CONFIG_MONGODB_ADMINUSERNAME:   "${MONGO_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD:   "${MONGO_ROOT_PASSWORD}"
      ME_CONFIG_MONGODB_AUTH_DATABASE:   admin
      ME_CONFIG_BASICAUTH_USERNAME:      "${ME_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD:      "${ME_PASSWORD}"

volumes:
  mongo-data:
